modLoader = "javafml"
loaderVersion = "[37,)"
license = "MIT"
issueTrackerURL="https://github.com/zomb-676/flighter/issues"
[[mods]]
modId = "fantasy_soup"
version = "${file.jarVersion}"
displayName = "fantasySoup"
displayURL="https://github.com/zomb-676/flighter"
logoFile = "logo.png"
credits = "Great thanks to Snownee , bosen and harbinger"
authors = "zomb_676,MaplayP,Meowsquito"
description = '''
lib for all my mod
'''
[[dependencies.fantasy_soup]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.fantasy_soup]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,1.18)"
ordering = "NONE"
side = "BOTH"
